#include "cert.h"

/// https://pki.goog/repository/

const char *rtdb_cert = "-----BEGIN CERTIFICATE-----\n"
                                 "MIIFVzCCAz+gAwIBAgINAgPlk28xsBNJiGuiFzANBgkqhkiG9w0BAQwFADBHMQsw\n"
                                 "CQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEU\n"
                                 "MBIGA1UEAxMLR1RTIFJvb3QgUjEwHhcNMTYwNjIyMDAwMDAwWhcNMzYwNjIyMDAw\n"
                                 "MDAwWjBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZp\n"
                                 "Y2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjEwggIiMA0GCSqGSIb3DQEBAQUA\n"
                                 "A4ICDwAwggIKAoICAQC2EQKLHuOhd5s73L+UPreVp0A8of2C+X0yBoJx9vaMf/vo\n"
                                 "27xqLpeXo4xL+Sv2sfnOhB2x+cWX3u+58qPpvBKJXqeqUqv4IyfLpLGcY9vXmX7w\n"
                                 "Cl7raKb0xlpHDU0QM+NOsROjyBhsS+z8CZDfnWQpJSMHobTSPS5g4M/SCYe7zUjw\n"
                                 "TcLCeoiKu7rPWRnWr4+wB7CeMfGCwcDfLqZtbBkOtdh+JhpFAz2weaSUKK0Pfybl\n"
                                 "qAj+lug8aJRT7oM6iCsVlgmy4HqMLnXWnOunVmSPlk9orj2XwoSPwLxAwAtcvfaH\n"
                                 "szVsrBhQf4TgTM2S0yDpM7xSma8ytSmzJSq0SPly4cpk9+aCEI3oncKKiPo4Zor8\n"
                                 "Y/kB+Xj9e1x3+naH+uzfsQ55lVe0vSbv1gHR6xYKu44LtcXFilWr06zqkUspzBmk\n"
                                 "MiVOKvFlRNACzqrOSbTqn3yDsEB750Orp2yjj32JgfpMpf/VjsPOS+C12LOORc92\n"
                                 "wO1AK/1TD7Cn1TsNsYqiA94xrcx36m97PtbfkSIS5r762DL8EGMUUXLeXdYWk70p\n"
                                 "aDPvOmbsB4om3xPXV2V4J95eSRQAogB/mqghtqmxlbCluQ0WEdrHbEg8QOB+DVrN\n"
                                 "VjzRlwW5y0vtOUucxD/SVRNuJLDWcfr0wbrM7Rv1/oFB2ACYPTrIrnqYNxgFlQID\n"
                                 "AQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E\n"
                                 "FgQU5K8rJnEaK0gnhS9SZizv8IkTcT4wDQYJKoZIhvcNAQEMBQADggIBAJ+qQibb\n"
                                 "C5u+/x6Wki4+omVKapi6Ist9wTrYggoGxval3sBOh2Z5ofmmWJyq+bXmYOfg6LEe\n"
                                 "QkEzCzc9zolwFcq1JKjPa7XSQCGYzyI0zzvFIoTgxQ6KfF2I5DUkzps+GlQebtuy\n"
                                 "h6f88/qBVRRiClmpIgUxPoLW7ttXNLwzldMXG+gnoot7TiYaelpkttGsN/H9oPM4\n"
                                 "7HLwEXWdyzRSjeZ2axfG34arJ45JK3VmgRAhpuo+9K4l/3wV3s6MJT/KYnAK9y8J\n"
                                 "ZgfIPxz88NtFMN9iiMG1D53Dn0reWVlHxYciNuaCp+0KueIHoI17eko8cdLiA6Ef\n"
                                 "MgfdG+RCzgwARWGAtQsgWSl4vflVy2PFPEz0tv/bal8xa5meLMFrUKTX5hgUvYU/\n"
                                 "Z6tGn6D/Qqc6f1zLXbBwHSs09dR2CQzreExZBfMzQsNhFRAbd03OIozUhfJFfbdT\n"
                                 "6u9AWpQKXCBfTkBdYiJ23//OYb2MI3jSNwLgjt7RETeJ9r/tSQdirpLsQBqvFAnZ\n"
                                 "0E6yove+7u7Y/9waLd64NnHi/Hm3lCXRSHNboTXns5lndcEZOitHTtNCjv0xyBZm\n"
                                 "2tIMPNuzjsmhDYAPexZ3FL//2wmUspO8IFgV6dtxQ/PeEMMA3KgqlbbC1j+Qa3bb\n"
                                 "bP6MvPJwNQzcmRk13NfIRmPVNnGuV/u3gm3c\n"
                                 "-----END CERTIFICATE-----\n";

const char *storage_cert = "-----BEGIN CERTIFICATE-----\n"
                                    "MIIESjCCAzKgAwIBAgINAeO0mqGNiqmBJWlQuDANBgkqhkiG9w0BAQsFADBMMSAw\n"
                                    "HgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMjETMBEGA1UEChMKR2xvYmFs\n"
                                    "U2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0xNzA2MTUwMDAwNDJaFw0yMTEy\n"
                                    "MTUwMDAwNDJaMEIxCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVHb29nbGUgVHJ1c3Qg\n"
                                    "U2VydmljZXMxEzARBgNVBAMTCkdUUyBDQSAxTzEwggEiMA0GCSqGSIb3DQEBAQUA\n"
                                    "A4IBDwAwggEKAoIBAQDQGM9F1IvN05zkQO9+tN1pIRvJzzyOTHW5DzEZhD2ePCnv\n"
                                    "UA0Qk28FgICfKqC9EksC4T2fWBYk/jCfC3R3VZMdS/dN4ZKCEPZRrAzDsiKUDzRr\n"
                                    "mBBJ5wudgzndIMYcLe/RGGFl5yODIKgjEv/SJH/UL+dEaltN11BmsK+eQmMF++Ac\n"
                                    "xGNhr59qM/9il71I2dN8FGfcddwuaej4bXhp0LcQBbjxMcI7JP0aM3T4I+DsaxmK\n"
                                    "FsbjzaTNC9uzpFlgOIg7rR25xoynUxv8vNmkq7zdPGHXkxWY7oG9j+JkRyBABk7X\n"
                                    "rJfoucBZEqFJJSPk7XA0LKW0Y3z5oz2D0c1tJKwHAgMBAAGjggEzMIIBLzAOBgNV\n"
                                    "HQ8BAf8EBAMCAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1Ud\n"
                                    "EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFJjR+G4Q68+b7GCfGJAboOt9Cf0rMB8G\n"
                                    "A1UdIwQYMBaAFJviB1dnHB7AagbeWbSaLd/cGYYuMDUGCCsGAQUFBwEBBCkwJzAl\n"
                                    "BggrBgEFBQcwAYYZaHR0cDovL29jc3AucGtpLmdvb2cvZ3NyMjAyBgNVHR8EKzAp\n"
                                    "MCegJaAjhiFodHRwOi8vY3JsLnBraS5nb29nL2dzcjIvZ3NyMi5jcmwwPwYDVR0g\n"
                                    "BDgwNjA0BgZngQwBAgIwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly9wa2kuZ29vZy9y\n"
                                    "ZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAGoA+Nnn78y6pRjd9XlQWNa7H\n"
                                    "TgiZ/r3RNGkmUmYHPQq6Scti9PEajvwRT2iWTHQr02fesqOqBY2ETUwgZQ+lltoN\n"
                                    "FvhsO9tvBCOIazpswWC9aJ9xju4tWDQH8NVU6YZZ/XteDSGU9YzJqPjY8q3MDxrz\n"
                                    "mqepBCf5o8mw/wJ4a2G6xzUr6Fb6T8McDO22PLRL6u3M4Tzs3A2M1j6bykJYi8wW\n"
                                    "IRdAvKLWZu/axBVbzYmqmwkm5zLSDW5nIAJbELCQCZwMH56t2Dvqofxs6BBcCFIZ\n"
                                    "USpxu6x6td0V7SvJCCosirSmIatj/9dSSVDQibet8q/7UK4v4ZUN80atnZz1yg==\n"
                                    "-----END CERTIFICATE-----\n";

const char *https_cert =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDvDCCAqSgAwIBAgINAgPk9GHsmdnVeWbKejANBgkqhkiG9w0BAQUFADBMMSAw\n"
    "HgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMjETMBEGA1UEChMKR2xvYmFs\n"
    "U2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0wNjEyMTUwODAwMDBaFw0yMTEy\n"
    "MTUwODAwMDBaMEwxIDAeBgNVBAsTF0dsb2JhbFNpZ24gUm9vdCBDQSAtIFIyMRMw\n"
    "EQYDVQQKEwpHbG9iYWxTaWduMRMwEQYDVQQDEwpHbG9iYWxTaWduMIIBIjANBgkq\n"
    "hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAps8kDr4ubyiZRULEqz4hVJsL03+EcPoS\n"
    "s8u/h1/Gf4bTsjBc1v2t8Xvc5fhglgmSEPXQU977e35ziKxSiHtKpspJpl6op4xa\n"
    "Ebx6guu+jOmzrJYlB5dKmSoHL7Qed7+KD7UCfBuWuMW5Oiy81hK561l94tAGhl9e\n"
    "SWq1OV6INOy8eAwImIRsqM1LtKB9DHlN8LgtyyHK1WxbfeGgKYSh+dOUScskYpEg\n"
    "vN0L1dnM+eonCitzkcadG6zIy+jgoPQvkItN+7A2G/YZeoXgbfJhE4hcn+CTClGX\n"
    "ilrOr6vV96oJqmC93Nlf33KpYBNeAAHJSvo/pOoHAyECjoLKA8KbjwIDAQABo4Gc\n"
    "MIGZMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSb\n"
    "4gdXZxwewGoG3lm0mi3f3BmGLjAfBgNVHSMEGDAWgBSb4gdXZxwewGoG3lm0mi3f\n"
    "3BmGLjA2BgNVHR8ELzAtMCugKaAnhiVodHRwOi8vY3JsLmdsb2JhbHNpZ24ubmV0\n"
    "L3Jvb3QtcjIuY3JsMA0GCSqGSIb3DQEBBQUAA4IBAQANeX81Z1YqDIs4EaLjG0qP\n"
    "OxIzaJI/y4kiRj3a+y3KOx74clIkLuMgi/9/5iv/n+1LyhGU9g7174slbzJOPbSp\n"
    "p1eT19ST2mYbdgTLx/hm3tTLoHIY/w4ZbnQYwfnPwAG4RefnEFYPQJmpD+Wh8BJw\n"
    "Bgtm2drTale/T6NBwmwnEFunfaMfMX3g6IBrx7VKnxIkJh/3p190WveLKgl9n7i5\n"
    "SWce/4woPimEn9WfEQWRvp6wKhaCKFjuCMuulEZusoOUJ4LfJnXxcuQTgIrSnwI7\n"
    "KfSSjsd42w3lX1fbgJp7vPmLM6OBRvAXuYRKTFqMAWbb7OaGIEE+cbxY6PDepnva\n"
    "-----END CERTIFICATE-----\n";


const char *service_account_key  = "-----BEGIN PRIVATE KEY-----\n"
                                   "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvDcM1BySC8Ezh\n"
                                   "IPyjbbXaxptgaMVcInGeEb2VhXLKjmdYjCBRo2Wc9Ad1Ik+0g/lH+PVSMKfF9GvX\n"
                                   "2fpjt1XiyDn/1bnNH/TusPrhiupWkUJSkXbMRlVtA+HJPoLlx91tgDhghvhRtKWw\n"
                                   "KbYmW3VnCFMiSoZXNhwbrWXvKnxiYXAQIfJKAsE2nnhvxLvrJCh4pnLMqp7HEYhs\n"
                                   "sg3Yw9tYU91RyNAidSIgjnKtxvWBA+noo5/nEz0RO+uOuI9u857oAT1sZzw/SD40\n"
                                   "uTmmZYLmhxixPk1wu6WXCED4XJnk1P/9WfSZieanxz7PljFCvf+ew8inesg5J3IT\n"
                                   "FUIvDo3JAgMBAAECggEAC7RL/WFMQMh8HW/ZEHzLBFUT6bTroDrJ1beqMUN+TrqJ\n"
                                   "gKdC2G6IQl+jGYL5KRDLY7NqxKtt5kuOw9yGVDE7h/ma/ibuQL+unuB8r8Sb4Tye\n"
                                   "XnqtIqCfwNWZ/LyGIEK2JIaGjnarxvvA+ce6LvOdxI0vEMuCkrVymOultYFl1maA\n"
                                   "m1X+4PlzWA6adLWHgfx+u/R/zIB2PnLevkyFTG/TYx4fiKQdZKEf87UIBg5GFjGH\n"
                                   "ySwRHJl/dEDBVq6AuAr3hlsYwTI1CAvv9NxC6U5xkugseZe/BZKnTHM6MfzZFcR7\n"
                                   "ka4OX1gAjXYQbPIarjKDXt3px4bJxADe+SFjb7YOMQKBgQDxkH4i8HC5LaA2esaJ\n"
                                   "X/m1p+em2dmog+mtQ6V/i8GEpu/MWJkQ0a9mzq2YC6m5cAYvWSyMyXgHmDd19kUa\n"
                                   "Oi+z39imJeatXU9aolwl0Fd94s3K8iT3zdaxE4mYbtNyzg+AhYUO/oIlw6NZpSmU\n"
                                   "weLaCNoLKUh116ibLTDMqhBJcQKBgQC5g8ZLv2kpLqCtvioRPeyAH8Ff1JFAo611\n"
                                   "A2yVBZowXv/+jgutP6sMv6mWZeR4CBqkTAKomgwMe2SpRh0hPFlwbZSG/NVrCHH7\n"
                                   "5QTHJxaBUS12N7p8edXD90AFXYTpriAkhEaOBYM4iQYGp+RgmkmoAZVtkxQjBukl\n"
                                   "12AOIpad2QKBgQC2n3Bc5b2yoYW/6i3yaXaVGO0OvR/KQIAHF18k//k7WiFsMYb2\n"
                                   "qi+a36Fpk1eq88AZR6dggGeYBkHXkmlHnLm3mQFnCrxMUIDPmnNjuxCKAU9noIzG\n"
                                   "Mv2ePZEGhrKg1pvtpAOmBE9MUY1LFoxLBBGGmK6PRZScUoALYKzF7cQGYQKBgDXs\n"
                                   "sfVOvFi2LwqR3lSItXhAwssCVP5/FWqQBj4DFOC+nJb33zkK6sOX6snG8HRblrLv\n"
                                   "TU6JCLuQGqCBuvHwQudFUwkx8S9dkxRva8Yf/JC2cgqNBG4uVA7Ujg2BM6NhdAJp\n"
                                   "WMDrpUsHuXKx1talwodNfowNVqsf1SGky00QjMtxAoGBAL6MjHWn4IT/Ly+fLZsY\n"
                                   "spO4hQBzQVI2NHEiiWiOQhXjRuH+gVQenaVDLrlDvvd710FE9sCT836mQUPG1WOl\n"
                                   "dpkVu/3zvTW0hiAQeJEfW/vYO+mIOqRmYtl5uetF8mGTI3meV2e1qcfVtEW+BHz1\n"
                                   "csP42SONNUjQVwiJCI4PyoTl\n-----END PRIVATE KEY-----\n";